#!/bin/bash

echo "Step 1: Click 'Start lab' button"
echo ""
echo "Step 2: Wait for lab to show 'Ready' status"
echo ""
echo "Step 3: Click in the 'AWS CLI' text box"
echo ""
echo "Step 4: Copy all credentials (4 lines starting with export)"
echo ""
echo "Step 5: Open terminal and paste the credentials"
echo ""
echo "Step 6: Run these commands to get IntelliNemo details:"
echo ""
echo "# Check if IntelliNemo is deployed"
echo "aws cloudformation list-stacks --query 'StackSummaries[?contains(StackName, \`intellinemo\`)].{Name:StackName,Status:StackStatus}' --output table"
echo ""
echo "# Get Lambda functions"
echo "aws lambda list-functions --query 'Functions[?contains(FunctionName, \`intellinemo\`)].FunctionName'"
echo ""
echo "# Get EKS clusters"
echo "aws eks list-clusters --query 'clusters[?contains(@, \`intellinemo\`)]'"
echo ""
echo "# Get CloudWatch alarms"
echo "aws cloudwatch describe-alarms --query 'MetricAlarms[?contains(AlarmName, \`intellinemo\`)].AlarmName'"