#!/bin/bash

echo "AWS Lab Setup for IntelliNemo Agent"
echo "=================================="
echo ""
echo "1. Click 'Start lab' button"
echo "2. Wait for lab to start (green dot)"
echo "3. Click 'AWS CLI' text box and copy all credentials"
echo "4. Paste in terminal and run:"
echo ""
echo "   export AWS_ACCESS_KEY_ID=AKIA..."
echo "   export AWS_SECRET_ACCESS_KEY=..."
echo "   export AWS_SESSION_TOKEN=..."
echo "   export AWS_DEFAULT_REGION=us-east-1"
echo ""
echo "5. Test connection:"
echo "   aws sts get-caller-identity"
echo ""
echo "6. View existing IntelliNemo stacks:"
echo "   aws cloudformation list-stacks --query 'StackSummaries[?contains(StackName, \`intellinemo\`)].{Name:StackName,Status:StackStatus}' --output table"
echo ""
echo "7. Check Lambda functions:"
echo "   aws lambda list-functions --query 'Functions[?contains(FunctionName, \`intellinemo\`)].FunctionName'"
echo ""
echo "8. For SSH access, click 'Download PEM' and:"
echo "   chmod 400 ~/Downloads/labsuser.pem"